openapi: '3.0.0'
info:
    title: 'API do PPF-CRM'
    version: '1.0.0'
    description: 'Documentação das rotas da API do PPF-CRM'
tags:
    - name: 'Users'
      description: 'Operações relacionadas aos usuários'
    - name: 'Teams'
      description: 'Operações relacionadas aos times'
    - name: 'Tasks'
      description: 'Operações relacionadas às tasks'
    - name: 'Requests'
      description: 'Endpoints associados às solicitações'
    - name: 'Notifications'
      description: 'Endpoints associados às notificações do sistema'
components:
    schemas:
        TaskStatus:
            type: string
            enum:
                - BACKLOG
                - TODO
                - DOING
                - STUCK
                - REVIEW
                - DONE
        TaskPriotiry:
            type: string
            enum:
                - BAIXA
                - NORMAL
                - ALTA
                - CRITICA
        NotificationStatus:
            type: string
            enum:
                - UNREAD
                - READ
paths:
    /v1/users/findWithFilter:
        get:
            tags:
                - Users
            summary: 'Busca usuários com filtros'
            parameters:
                - in: query
                  name: organizationId
                  schema:
                      type: number
                  required: true
                  description: 'ID da organização que os usuários pertence'
                - in: query
                  name: search
                  schema:
                      type: string
                  required: false
                  description: 'Nome ou email do usuário para filtragem opcional'
                - in: query
                    name: status
                    schema:
                        type: string
                        enum:
                            - ATIVO
                            - INATIVO
                            - PENDENTE
            responses:
                200:
                    description: 'Retorna um JSON com uma lista dos usuários buscados no banco seguindo os filtros inseridos'

    /v1/users/getUsersByOrganizationId/{organizationId}:
        get:
            tags:
                - Users
            summary: 'Busca usuários pelo ID da organização'
            parameters:
                - in: path
                  name: organizationId
                  schema:
                      type: number
                  required: true
                  description: 'ID da organização que os usuários pertence'
            responses:
                200:
                    description: 'Retorna um JSON com uma lista dos usuários da organização'
    /v1/team/findAllByUserId/:
        get:
            tags:
                - Teams
            summary: 'Busca os times que o usuário faz parte pelo seu ID'
            parameters:
                - in: query
                  name: userId
                  schema:
                      type: number
                  required: true
                  description: 'ID do usuário que quer buscar os times que faz parte'
                - in: query
                  name: teamName
                  schema:
                      type: string
                  required: false
                  description: 'Nome do time para filtragem opcional'
            responses:
                200:
                    description: 'Retorna um JSON com uma lista dos times que o usuário pertence'
    /v1/tasks/:
        post:
            tags:
                - Tasks
            summary: 'Cria uma task no banco de dados'
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                title:
                                    type: string
                                    required: true
                                description:
                                    type: string
                                    required: false
                                status:
                                    $ref: '#/components/schemas/TaskStatus'
                                    required: true
                                priority:
                                    $ref: '#/components/schemas/TaskPriotiry'
                                    required: true
                                organizationId:
                                    type: number
                                    required: true
                                assignedTo:
                                    type: number
                                    required: false
                                createdBy:
                                    type: number
                                    required: true
                                deadline:
                                    type: string
                                    format: date-time
                                    required: false
                                projectId:
                                    type: number
                                    required: false
            responses:
                200:
                    description: Retorna um JSON com os dados da task criada
    /v1/request/:
        post:
            tags:
                - Requests
            summary: 'Cria uma solicitação no banco de dados'
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                title:
                                    type: string
                                    required: true
                                description:
                                    type: string
                                    required: false
                                priority:
                                    $ref: '#/components/schemas/TaskPriotiry'
                                    required: true
                                status:
                                    $ref: '#/components/schemas/TaskStatus'
                                    required: true
                                organizationId:
                                    type: number
                                    required: true
                                createdBy:
                                    type: number
                                    required: true
                                projectId:
                                    type: number
                                    required: false
                                resolutionDate:
                                    type: string
                                    format: date-time
                                    required: false
            responses:
                200:
                    description: Retorna um JSON com os dados da solicitação criad
                500:
                    description: Retorna um JSON com a mensagem de erro

    /v1/request/saveRequestAndNotification:
            post:
                tags:
                    - Requests
                summary: 'Cria uma solicitação e automaticamente cria uma notificação para os usuários que possuem relação com a solicitação'
                requestBody:
                    required: true
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    title:
                                        type: string
                                        required: true
                                    description:
                                        type: string
                                        required: false
                                    priority:
                                        $ref: '#/components/schemas/TaskPriotiry'
                                        required: true
                                    status:
                                        $ref: '#/components/schemas/TaskStatus'
                                        required: true
                                    organizationId:
                                        type: number
                                        required: true
                                    createdBy:
                                        type: number
                                        required: true
                                    projectId:
                                        type: number
                                        required: false
                                    resolutionDate:
                                        type: string
                                        format: date-time
                                        required: false
                responses:
                    200:
                        description: Retorna um JSON com os dados da solicitação criad
                    500:
                        description: Retorna um JSON com a mensagem de erro

    /v1/request/project/{projectId}:
        get:
            tags:
                - Requests
            summary: 'Busca uma solicitação no banco de dados através do ID do projeto'
            parameters: 
                - in: path
                  name: projectId
                  schema:
                      type: integer
                  required: true
                  description: 'ID do projeto que a solicitação pertence'

            responses:
                200:
                    description: Retorna um JSON com os dados do request
                500:
                    description: Retorna um JSON com a mensagem de erro

    /v1/request/{id}:
        get:
            tags:
                - Requests
            summary: 'Busca uma solicitação no banco de dados através do seu ID'
            parameters: 
                - in: path
                  name: id
                  schema:
                      type: integer
                  required: true
                  description: 'ID do projeto que a solicitação pertence'

            responses:
                200:
                    description: Retorna um JSON com os dados da solicitação
                500:
                    description: Retorna um JSON com a mensagem de erro

    /v1/request/update/{id}:
        put:
            tags:
                - Requests
            summary: 'Atualiza uma solicitação no banco de dados através do seu ID'
            parameters:
              - in: path
                name: id
                schema:
                  type: integer
                required: true
                description: 'ID da solicitação a ser atualizada'
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                title:
                                    type: string
                                description:
                                    type: string
                                priority:
                                    $ref: '#/components/schemas/TaskPriority'
                                status:
                                    $ref: '#/components/schemas/TaskStatus'
            responses:
                200:
                    description: Retorna um JSON com os dados da solicitação atualizada
                500:
                    description: Retorna um JSON com a mensagem de erro

    /v1/notification:
            post:
                tags:
                    - Notifications
                summary: 'Cria uma notificação no banco de dados'
                requestBody:
                    required: true
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    title:
                                        type: string
                                        required: true
                                    message:
                                        type: string
                                        required: false
                                    status:
                                        $ref: '#/components/schemas/NotificationStatus'
                                        required: true
                                    organizationId:
                                        type: integer
                                        required: true
                                    userId:
                                        type: integer
                                        required: true
                                    projectId:
                                        type: integer
                                        required: false
                                    requestId:
                                        type: integer
                                        required: false
                responses:
                    200:
                        description: Retorna um JSON com os dados da notificação criada
                    500:
                        description: Retorna um JSON com a mensagem de erro

    /v1/notification/update/{id}:
        put:
            tags:
                - Notifications
            summary: 'Atualiza uma notificação já existente no banco de dados'
            parameters:
              - in: path
                name: id
                schema:
                  type: integer
                required: true
                description: 'ID da solicitação a ser atualizada'
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                title:
                                    type: string
                                    required: true
                                message:
                                    type: string
                                    required: false
                                status:
                                    $ref: '#/components/schemas/NotificationStatus'
                                    required: true
                                organizationId:
                                    type: integer
                                    required: true
                                userId:
                                    type: integer
                                    required: true
                                projectId:
                                    type: integer
                                    required: false
                                requestId:
                                    type: integer
                                    required: false
            responses:
                200:
                    description: Retorna um JSON com os dados da notificação criada
                500:
                    description: Retorna um JSON com a mensagem de erro

    /v1/notification/markAsRead/{id}:
        put:
            tags:
                - Notifications
            summary: 'Atualiza uma notificação marcando ela como lida'
            parameters:
              - in: path
                name: id
                schema:
                  type: integer
                required: true
                description: 'ID da solicitação a ser atualizada'
            responses:
                200:
                    description: Retorna um JSON indicando se foi bem sucedido ou não
                500:
                    description: Retorna um JSON com a mensagem de erro   

    /v1/notification/findById/{id}:
        get:
            tags:
                - Notifications
            summary: 'Busca uma notificação pelo seu ID'
            parameters:
              - in: path
                name: id
                schema:
                  type: integer
                required: true
                description: 'ID da solicitação a ser buscada no banco de dados'
            responses:
                200:
                    description: Retorna um JSON indicando se foi bem sucedido ou não
                404:
                    description: A notificação com o ID inserido não foi encontrada
                500:
                    description: Retorna um JSON com a mensagem de erro 

    /v1/notification/getNotifications/{userId}:
        get:
            tags:
                - Notifications
            summary: 'Busca uma notificação pelo ID do usuário logado'
            parameters:
              - in: path
                name: userId
                schema:
                  type: integer
                required: true
                description: 'ID do usuário logado no sistema'
            responses:
                200:
                    description: Retorna um JSON indicando se foi bem sucedido ou não
                404:
                    description: A notificação com o ID inserido não foi encontrada
                500:
                    description: Retorna um JSON com a mensagem de erro

    /v1/notification/getUnreadCount/{userId}:
        get:
            tags:
                - Notifications
            summary: 'Busca o número de notificações não lidas pelo ID do usuário logado'
            parameters:
              - in: path
                name: userId
                schema:
                  type: integer
                required: true
                description: 'ID do usuário logado no sistema'
            responses:
                200:
                    description: Retorna o número de tarefas que ainda não foi visualizado
                500:
                    description: Retorna um JSON com a mensagem de erro do servidor

    /v1/notification/delete/{id}:
        delete:
            tags:
                - Notifications
            summary: 'Exclui uma notificação pelo seu ID'
            parameters:
              - in: path
                name: id
                schema:
                  type: integer
                required: true
                description: 'ID da notificação a ser excluída'
            responses:
                200:
                    description: Retorna um JSON indicando o sucesso da operação
                500:
                    description: Retorna um JSON com a mensagem de erro do servidor
